# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshabu < Formula
  desc "SSH client management tool"
  homepage "https://github.com/ratsky-oss/sshabu"
  version "0.1.3"
  license "Apache-2.0"

  depends_on "openssh" => :optional

  on_macos do
    on_intel do
      url "https://github.com/ratsky-oss/sshabu/releases/download/v0.1.3/sshabu_Darwin_x86_64.tar.gz"
      sha256 "13a5baa4094add5f377393dcbce1f51c545dca92743dfeefdfc0d8f043648ad8"

      def install
        bin.install "sshabu"
      end
    end
    on_arm do
      url "https://github.com/ratsky-oss/sshabu/releases/download/v0.1.3/sshabu_Darwin_arm64.tar.gz"
      sha256 "515471a2ad48681944cd875fafb0cab210dc40d025c30cb58074bbcb781557ba"

      def install
        bin.install "sshabu"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ratsky-oss/sshabu/releases/download/v0.1.3/sshabu_Linux_x86_64.tar.gz"
        sha256 "60e358fa5b1516d3c6433b788c06b7bc74b4c45a7f47bb32007d2335f9d73c0a"

        def install
          bin.install "sshabu"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ratsky-oss/sshabu/releases/download/v0.1.3/sshabu_Linux_arm64.tar.gz"
        sha256 "a0c74a21f14bb476568ee6e80544c68a08b4f948d9560c829039727514056c9b"

        def install
          bin.install "sshabu"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Use `sshabu init` to create configuration example in $HOME/.sshabu/ directory
    EOS
  end
end
