# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshabu < Formula
  desc "SSH client management tool"
  homepage "https://github.com/ratsky-oss/sshabu"
  version "0.1.2"
  license "Apache-2.0"

  depends_on "openssh" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ratsky-oss/sshabu/releases/download/v0.1.2/sshabu_Darwin_arm64.tar.gz"
      sha256 "8b8d23c455ecb8efdd9fb20c60a9cae369ab1caa2ce8df671c1076ce231a93bd"

      def install
        bin.install "sshabu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ratsky-oss/sshabu/releases/download/v0.1.2/sshabu_Darwin_x86_64.tar.gz"
      sha256 "5d66917335c8edbceaefe2a7a09d8e8530af89d53925bac36d0feb47344e68da"

      def install
        bin.install "sshabu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ratsky-oss/sshabu/releases/download/v0.1.2/sshabu_Linux_arm64.tar.gz"
      sha256 "7d89f5c7379f18bb006e44f2d4669a0797d4cda17507c0d44a52b318adbf80ea"

      def install
        bin.install "sshabu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ratsky-oss/sshabu/releases/download/v0.1.2/sshabu_Linux_x86_64.tar.gz"
      sha256 "1d92b8672173e673bdc12013528626557792e4c59b4e0e87f8a4dcb3594993ee"

      def install
        bin.install "sshabu"
      end
    end
  end

  def caveats
    <<~EOS
      Use `sshabu init` to create configuration example in $HOME/.sshabu/ directory
    EOS
  end
end
