# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshabu < Formula
  desc "SSH client management tool"
  homepage "https://github.com/ratsky-oss/sshabu"
  version "0.1.2"
  license "Apache-2.0"

  depends_on "openssh" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ratsky-oss/sshabu/releases/download/v0.1.2/sshabu_Darwin_x86_64.tar.gz"
      sha256 "ebb14aac024f26573c4d9b105644b734309e81f5c2abd2318d1d935be306c02d"

      def install
        bin.install "sshabu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ratsky-oss/sshabu/releases/download/v0.1.2/sshabu_Darwin_arm64.tar.gz"
      sha256 "6b30294b582e55da56666fef55206fefbddfa3bf291a4536e30ec4a41a62ba4b"

      def install
        bin.install "sshabu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ratsky-oss/sshabu/releases/download/v0.1.2/sshabu_Linux_arm64.tar.gz"
      sha256 "a5d78b0042acf3cfb351ea540b1b1a36c150aec6947dc8c752b94f6f3eb77146"

      def install
        bin.install "sshabu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ratsky-oss/sshabu/releases/download/v0.1.2/sshabu_Linux_x86_64.tar.gz"
      sha256 "9202ea93303d1f049bbb385714660df41cca6574340c20adab88a85192af0ef6"

      def install
        bin.install "sshabu"
      end
    end
  end

  def caveats
    <<~EOS
      Use `sshabu init` to create configuration example in $HOME/.sshabu/ directory
    EOS
  end
end
